"""
src/ingestion/data_loader.py
=============================
Loads transaction data from any supported source and normalises it
to the canonical schema used throughout the pipeline:

    sender_account | receiver_account | transaction_amount | timestamp | is_fraud

Supported sources:
  - PaySim CSV  (your existing dataset)
  - AMLSim CSV
  - Synthetic   (generated by data_generator.py)
  - Any CSV that can be column-mapped
"""

import pandas as pd
import numpy as np
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..'))
from config.config import *
from src.ingestion.data_generator import generate_synthetic_dataset


# ── Column mapping definitions ────────────────────────────────────────────────
# Keys = canonical name, values = known aliases in raw datasets
COLUMN_ALIASES = {
    "sender_account":    ["nameOrig", "sender", "source_account",
                          "from_account", "sender_account", "orig"],
    "receiver_account":  ["nameDest", "receiver", "dest_account",
                          "to_account", "receiver_account", "dest"],
    "transaction_amount":["amount", "transaction_amount", "tx_amount",
                          "value", "amt"],
    "timestamp":         ["step", "timestamp", "date", "time",
                          "transaction_date", "ts"],
    "is_fraud":          ["isFraud", "is_fraud", "fraud", "label",
                          "isFlaggedFraud"],
}


def _resolve_columns(df: pd.DataFrame) -> dict[str, str]:
    """Return mapping {canonical_name: actual_column_name_in_df}."""
    resolved = {}
    for canon, aliases in COLUMN_ALIASES.items():
        for alias in aliases:
            if alias in df.columns:
                resolved[canon] = alias
                break
    return resolved


def _normalise(df: pd.DataFrame, col_map: dict[str, str],
               source_name: str) -> pd.DataFrame:
    """Rename columns to canonical names and cast types."""
    out = pd.DataFrame()

    # Required columns
    for req in ["sender_account", "receiver_account", "transaction_amount"]:
        if req not in col_map:
            raise ValueError(f"[{source_name}] Cannot find column for '{req}'. "
                             f"Available: {list(df.columns)}")
        out[req] = df[col_map[req]].astype(str)

    out["transaction_amount"] = pd.to_numeric(
        df[col_map["transaction_amount"]], errors="coerce"
    ).fillna(0).abs()

    # Timestamp — handle both datetime and integer step columns
    if "timestamp" in col_map:
        raw_ts = df[col_map["timestamp"]]
        if pd.api.types.is_numeric_dtype(raw_ts):
            # PaySim 'step' = hours since epoch → convert to datetime
            base = pd.Timestamp("2023-01-01")
            out["timestamp"] = base + pd.to_timedelta(raw_ts, unit="h")
        else:
            out["timestamp"] = pd.to_datetime(raw_ts, errors="coerce")
    else:
        # No time column — generate synthetic monotonic timestamps
        out["timestamp"] = pd.date_range(
            "2023-01-01", periods=len(df), freq="1min"
        )

    # Label — optional
    if "is_fraud" in col_map:
        out["is_fraud"] = pd.to_numeric(
            df[col_map["is_fraud"]], errors="coerce"
        ).fillna(0).astype(int)
    else:
        out["is_fraud"] = 0   # unknown → treat as unlabelled

    return out.dropna(subset=["sender_account", "receiver_account"])


def load_paysim(path=None, sample_n: int = None) -> pd.DataFrame:
    """
    Load PaySim CSV.
    Handles both versions:
      - with  'step' column (original PaySim)
      - without 'step' column (your version)
    """
    path = path or PAYSIM_PATH
    print(f"Loading PaySim from {path}...")
    df = pd.read_csv(path)

    # Filter to money-moving transaction types
    if "type" in df.columns:
        df = df[df["type"].isin(["TRANSFER", "CASH_OUT"])].copy()
        print(f"  Filtered to TRANSFER/CASH_OUT: {len(df):,} rows")

    col_map = _resolve_columns(df)
    out = _normalise(df, col_map, "PaySim")
    out = out.sort_values("timestamp").reset_index(drop=True)
    out["source"] = "paysim"

    if sample_n and len(out) > sample_n:
        out = out.sample(sample_n, random_state=RANDOM_STATE).reset_index(drop=True)
        print(f"  Sampled to {sample_n:,} rows")

    _print_summary(out, "PaySim")
    return out


def load_amlsim(path=None, sample_n: int = None) -> pd.DataFrame:
    """Load AMLSim transaction log."""
    path = path or AMLSIM_PATH
    print(f"Loading AMLSim from {path}...")
    df = pd.read_csv(path)
    col_map = _resolve_columns(df)
    out = _normalise(df, col_map, "AMLSim")
    out = out.sort_values("timestamp").reset_index(drop=True)
    out["source"] = "amlsim"

    if sample_n and len(out) > sample_n:
        out = out.sample(sample_n, random_state=RANDOM_STATE).reset_index(drop=True)

    _print_summary(out, "AMLSim")
    return out


def load_synthetic(path=None, regenerate: bool = False) -> pd.DataFrame:
    """Load or regenerate synthetic dataset."""
    path = path or SYNTHETIC_TX
    if regenerate or not path.exists():
        print("Generating fresh synthetic dataset...")
        return generate_synthetic_dataset(save=True)

    print(f"Loading synthetic dataset from {path}...")
    df = pd.read_csv(path, parse_dates=["timestamp"])
    df["source"] = "synthetic"
    _print_summary(df, "Synthetic")
    return df


def load_csv(path: str, column_map: dict = None) -> pd.DataFrame:
    """
    Generic loader for any CSV with optional manual column mapping.
    column_map: {canonical_name: actual_column_name}
    """
    print(f"Loading CSV from {path}...")
    df = pd.read_csv(path)
    if column_map:
        col_map = column_map
    else:
        col_map = _resolve_columns(df)
    out = _normalise(df, col_map, path)
    out["source"] = "custom"
    _print_summary(out, path)
    return out


def _print_summary(df: pd.DataFrame, name: str):
    """Print a concise data summary."""
    print(f"\n  [{name}] Loaded {len(df):,} transactions")
    print(f"  Unique senders   : {df['sender_account'].nunique():,}")
    print(f"  Unique receivers : {df['receiver_account'].nunique():,}")
    print(f"  Amount range     : {df['transaction_amount'].min():,.2f} – "
          f"{df['transaction_amount'].max():,.2f}")
    print(f"  Date range       : {df['timestamp'].min().date()} → "
          f"{df['timestamp'].max().date()}")
    if df["is_fraud"].sum() > 0:
        print(f"  Fraud rate       : {df['is_fraud'].mean():.4%}")
    else:
        print(f"  Fraud labels     : not available")
    print()
